---
title: "Fantasy Solver"
author: "Colin Poska"
date: "11/10/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Call in the libraries
```{r}
library(lpSolveAPI)
library(tidyverse)
library(dplyr)
library(tidyr)
library(utils)
```

##Import the data
```{r}
DKSalaries_Import <- read.csv("NBA-classic-import.csv")
```

##Final Prep
```{r}
DKSalaries <- DKSalaries_Import

#Creating constraints for the solver to follow, this section below creates constraints by position
DKSalaries <- DKSalaries[complete.cases(DKSalaries),]
DKSalaries <- cbind(DKSalaries, PG=ifelse(DKSalaries$Roster.Position=="PG",1,0))
DKSalaries <- cbind(DKSalaries, SG=ifelse(DKSalaries$Roster.Position=="SG",1,0))
DKSalaries <- cbind(DKSalaries, SF=ifelse(DKSalaries$Roster.Position=="SF",1,0))
DKSalaries <- cbind(DKSalaries, PF=ifelse(DKSalaries$Roster.Position=="PF",1,0))
DKSalaries <- cbind(DKSalaries, C=ifelse(DKSalaries$Roster.Position=="C",1,0))
DKSalaries <- cbind(DKSalaries, G=ifelse(DKSalaries$Roster.Position=="G",1,0))
DKSalaries <- cbind(DKSalaries, F=ifelse(DKSalaries$Roster.Position=="F",1,0))
DKSalaries <- cbind(DKSalaries, UTIL=ifelse(DKSalaries$Roster.Position=="UTIL",1,0))
DKSalaries <- cbind(DKSalaries, X=1) 

#This creates a constraint on each player name to make sure each player is used once
Players <- sort(unique(DKSalaries$Name))
DKSalaries[Players] <- list(numeric())
test <- sapply(17:(length(Players)+17), function(n) ifelse(as.character(DKSalaries$Name) == as.character(colnames(DKSalaries)[n]), DKSalaries[,n] <- 1, DKSalaries[,n] <- 0))


Final <- cbind(DKSalaries[1:16],test)

#Somehow needed this to run.  I just leave this here to be safe
Final$Ownership <- as.numeric(Final$Ownership)
Final$Projections <- as.numeric(Final$Projections)

#Create a new data frame, now repeat the same process we did for players but by team
FinalTwo <- Final
Teams <- sort(unique(DKSalaries$Team))
DKSalaries[Teams] <- list(numeric())
length <- ncol(FinalTwo)
test <- sapply(length:(length(Teams)+length), function(n) ifelse(as.character(DKSalaries$Team) == as.character(colnames(DKSalaries)[n]), DKSalaries[,n] <- 1, DKSalaries[,n] <- 0))
Final3 <- cbind(FinalTwo,test)
Final3 <- Final3[,-c(ncol(Final),ncol(Final3))]




```

##Run this before you run the solver
```{r}
#Resets the export data frame
Projected_Score <- 2500
export12<- data.frame()
check <- 0
final.columns <- ncol(Final3)




```


##The solver
```{r}
#Repeat loop that runs forever.  Set to stop after the first three lineups.  Check export12 after that to make sure the solver is working.  Change the three at the bottom if you want to make a specific amount of lineups
repeat{
  #This is all from the solver api.  Creating the linear programming model, adding constraints and solving
Num_Players <- length(Final3$X)



lp_model = make.lp(0, Num_Players)
set.objfn(lp_model, Final3$Projections)

lp.control(lp_model, sense= "max")
set.type(lp_model, 1:Num_Players, "binary")

add.constraint(lp_model, Final3$Salary, "<=",50000)
add.constraint(lp_model, Final3$Projections, "<=",Projected_Score - .001) #Creates the next best optimal lineup.  Prevents repeat lineups
add.constraint(lp_model, Final3$PG, "=",1)
add.constraint(lp_model, Final3$SG, "=",1)
add.constraint(lp_model, Final3$SF, "=",1)
add.constraint(lp_model, Final3$PF, "=",1)
add.constraint(lp_model, Final3$C, "=",1)
add.constraint(lp_model, Final3$F,  "=",1)
add.constraint(lp_model, Final3$G,  "=",1)
add.constraint(lp_model, Final3$UTIL,  "=",1)
vector <- sapply(17:(length(Players)+17), function(n) add.constraint(lp_model, Final3[,n],  "<=",1))
  vector

vector2 <- sapply((final.columns-4):final.columns, function(n) add.constraint(lp_model, Final3[,n],  "<=",3))
  vector2

add.constraint(lp_model, Final3$X, "=",8)


solve(lp_model)

Projected_Score <- crossprod(Final3$Projections,get.variables(lp_model))
Cost <- crossprod(Final3$Salary,get.variables(lp_model))
Owned <- crossprod(Final3$Ownership,get.variables(lp_model))

optimal_lineup <- subset(data.frame(Final3$NameID, Final3$Roster.Position), get.variables(lp_model) == 1)


#This sorts the lineups so they can be copied and pasted into the DKentries csv
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "PG"){
    a <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "SG"){
    b <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "SF"){
    c<- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "PF"){
    d <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "C"){
    e<- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "G"){
    f <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "F"){
    g <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
aa <- 0
for(i in 1:8){
  if(optimal_lineup$Final3.Roster.Position[i] == "UTIL"){
    h <- optimal_lineup$Final3.NameID[i]
    optimal_lineup <- optimal_lineup[-i,]
    aa <- aa + 1
  }
  if(aa == 1){break  }}
lineups <- data.frame(PG=a,SG=b,SF=c,PF=d,C=e,G=f,F=g,UTIL=h,Projections = Projected_Score, Cost = Cost, Owned = Owned)


export12 <- rbind(export12,lineups)
#Saving the lineups to a csv in case the data frame gets deleted/program crashes
write.csv(export12,'backuplineups.csv')
check <- check + 1
if(check == 3){
  break
}
}

```

##Sort the lineups, export all lineups being used
```{r}

sorted.lineups <- subset(export12,Cost > 49601)
sorted.lineups <- sorted.lineups[order(-sorted.lineups$Cost),]


sorted.lineups <- sorted.lineups[1:85,]

write.csv(Don, 'Draftkings.entries.csv')
```


